### ISSUE TITLE
Not able to play rtmp from AWS Cloudfront RTMP distribution

### ISSUE THREAD

**Issue by daniel2surf** [flavioribeiro/clappr-rtmp-plugin#57] opened 2016-08-12 21:34 UTC
I can reproduce with no problem here on the their debug player: http://d1k5ny0m6d4zlj.cloudfront.net/diag/CFStreamingDiag.html

My setup is ok, cause it works fine when playing rtmp from nginx server.
I also can play the RTMP vod file from wowza flash player: 
https://www.wowza.com/testplayers

host: rtmp://rtmp.conanewborn.com.br:1935/cfx/st
file/stream: entrada

My player setup:

<script>
        var player = new Clappr.Player({
        source: "rtmp://rtmp.conanewborn.com.br:1935/cfx/st/entrada",
        poster: "poster.jpg",
        parentId: "#player_57ae3ed6cd36f",
        plugins: { container: [TextOverlay], playback: [RTMP] },
        textOverlay: "test",        
        rtmpConfig: {
            swfPath: '//cdn.jsdelivr.net/clappr.rtmp/latest/assets/RTMP.swf',
            scaling:'stretch',
            playbackType: 'vod',
            bufferTime: 1,
            startLevel: 0
        }
      });
    </script> 

Does anybody knows if that is a limitation or bug? Any tip?
Thanks

**Comment by gfronza** [comment] 2016-08-15 15:55
@daniel2surf 

I tried to reproduce this stream URL
rtmp://rtmp.conanewborn.com.br:1935/cfx/st/entrada But I'm getting StreamNotFound.

Can you provide me with another valid URL?

**Comment by daniel2surf** [comment] 2016-08-15 15:59
@gfronza I just tried again... And it is playing...
Can you try again here: http://d1k5ny0m6d4zlj.cloudfront.net/diag/CFStreamingDiag.html
Streaming distribuition: rtmp.conanewborn.com.br
Video filename: entrada
Thanks

**Comment by gfronza** [comment] 2016-08-15 18:03
Ok now it's working! Thanks!

**Comment by gfronza** [comment] 2016-08-15 19:00
@daniel2surf I added some logging and noticed a security error when loading the URL. The streaming is not playing because of that. I'll add more debugging lines to help identify those cases.

**Comment by daniel2surf** [comment] 2016-08-15 20:04
@gfronza If the other rtmp players are able to play it, Clappr RTMP should play as well... Don't you think?
Any idea how to solve it?

**Comment by gfronza** [comment] 2016-08-15 20:55
@daniel2surf Yes, but so far I couldn't identify the reason for this `MediaErrorEvent` Connection Failed. I'll have to rebuild Adobe OSMF with logging directive enabled to have a more detailed view of the problem.

**Comment by gfronza** [comment] 2016-08-15 22:08
@daniel2surf I found the issue. OSMF (a very old Adobe project) is ruling out the application instance in the path (in your case the app instance is `st`. Then, when trying to connect to app /cfx without specifying the instance name, the result is `Connection failed.`. I never noticed this because all streaming servers I worked with used the default instance (`_definst_`) and OSFM has a special treatment for it (rsrs).

I have a "fork" of the OSMF project and will make the fix.

**Comment by daniel2surf** [comment] 2016-08-15 22:11
@gfronza Haha...
AWS Cloudfront RTMP is the first one behaving this way for me as well...
Good Job! Thanks

**Comment by gfronza** [comment] 2016-08-17 14:53
@daniel2surf I found out the the fix is that as simple as I first thought :(
As a temporary solution, is it possible for you to use the default instance? (_definst_)? I'm still thinking on how I'm going to solve this without breaking anything.

**Comment by daniel2surf** [comment] 2016-08-18 22:04
@gfronza Thanks for your effort. I cannot use default instance as it is all setup by aws cloudfront distribuition... The "/cfx/st/" is their standard path...
I'm using a nginx-rtmp for now... 
What do you think about using as parameters: host and filename. So it would be passed to the rtmp plugin and the swf player...

**Comment by gfronza** [comment] 2016-08-19 13:19
@daniel2surf Adding host and filename/streamname as arguments wouldn't be a clappr-like solution. So I decided to add a boolean parameter called `useAppInstance`. In your case you just have to set it to `true`.

https://github.com/flavioribeiro/clappr-rtmp-plugin/releases/tag/0.0.14

Let me know if I can close this issue (after your validation).

**Comment by daniel2surf** [comment] 2016-08-19 19:18
@gfronza Still not able to play... Using your rtmp.min.js release...
Here is the code i'm using:
<script type='text/javascript' src='https://cdn.jsdelivr.net/clappr/latest/clappr.min.js'></script>
<script type='text/javascript' src='player/rtmp.min.js'></script>

<div id="player_57b75a3a5fc18" class="player"></div> 
  <script>
        var player = new Clappr.Player({
        source: "rtmp://rtmp.conanewborn.com.br:1935/cfx/st/entrada",
        poster: "poster.jpg",
        parentId: "#player_57b75a3a5fc18",
        plugins: {  playback: [RTMP] },
        rtmpConfig: {
            swfPath: '//cdn.jsdelivr.net/clappr.rtmp/latest/assets/RTMP.swf',
            scaling:'stretch',
            playbackType: 'vod',
            useAppInstance: true,
            bufferTime: 1,
            startLevel: 0
        }
      });
    </script>

**Comment by gfronza** [comment] 2016-08-19 19:25
@daniel2surf the CDN (jsdelivr) is outdated due to the repo ownership change. We already asked them to update, but nothing so far. You'll have to host the SWF file yourself for now.

**Comment by daniel2surf** [comment] 2016-08-19 19:39
@gfronza Working perfect now... Thanks a lot!

**Closed** 2016-08-19 19:43 UTC
